/***************************************************************************
 *
 * R2RML Model : RefPredicateMap interface
 *
 * (C) 2011 Antidot (http://www.antidot.net)
 *
 * Module			:	R2RMLModel
 * 
 * Fichier			:	IRefPredicateMap.java
 *
 * Description		:	An element of a class which implements this interface
 * 						contains the rules for generating the predicate 
 * 						component of the (predicate, object) pair generated
 * 						by a RefPredicateObjectMap.
 * 
 * Reference		:	RDF Vocabulary for R2RML
 * 						R2RML: RDB to RDF Mapping Language
 * 						W3C Working Draft 24 March 2011
 *
 * Options de compilation:
 *
 * Auteurs(s)			:	JHO
 *
 *
 ****************************************************************************/
package antidot.r2rml.model;

import org.openrdf.model.URI;

/**
 * @author   jh
 */
public interface IRefPredicateMap {

	/**
	 * This property specifies an RDF property. The specified property will be used as the predicate for the (predicate, object) pair generated by the RefPredicateObjectMap.
	 * @return
	 */
	public URI getPredicate();

	/**
	 * @param  predicate
	 */
	public void setPredicate(URI predicate);

}
